- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print  information
      vars:
        Timings: 120 hours
      ansible.builtin.debug:
        msg: "Hi i am learning {{course}} from  {{Trainer}} in {{Duration}} and timings arre {{Timings}} "