- name: chekcing preference of variables
  hosts: localhost
  vars:
    WISHES: "MORNING from PLAY variable"
  # vars_files:
  # - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: Please enter wishes from prompt
    private: false
  tasks:
  - name: from tasks
    # vars:
    #   WISHES: "MORNING from TASK variable"
    ansible.builtin.debug:
      msg: "{{WISHES}}"



#preference
# 1.arguments
# 2. TASK
# 3. file
#4. 
      