- name: datatypes
  hosts: localhost
  vars:
    course: DEVOPS WITH AWS #string
    Tools: #list
    - ansible
    - jenkins
    - puppet
    Experience: #Map
      Devops: 3 #number
      AWS: 2
    RealProject: true #bool
  tasks:
    - name: leanring datatypes
      ansible.builtin.debug:
        msg: "HELLO I am leanring {{course}} and tools are {{Tools}} with experience as {{Experience}} and realprojects are {{RealProject}}"
