- name: conditions
  hosts: localhost
  become: yes
  tasks: 
  - name: check user
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
  
  - name: print user
    ansible.builtin.debug:
      msg: "userinfo is {{USER}}"
  
  - name: create user
    ansible.builtin.command: useradd expense
    #when the task should run 
    # acts same like if condition but no else condition
    when: USER.rc != 0

  - name: say hello
    ansible.builtin.debug:
      msg: "hello"