- name: filters
  hosts: localhost
  tasks: 
  - name: leanring filters
    ansible.builtin.debug:
      msg: "Prinitng variable {{Duration | default('3 months')}}"

  - name: lowercase
    vars: 
      course: "DEVOPS"
    ansible.builtin.debug:
      msg: "converting into lowercase {{course | lower}}"
  
  - name: uppercase
    vars: 
      course: "devops"
    ansible.builtin.debug:
      msg: "converting into uppercase {{course | upper}}"

  - name: removing duplicates
    vars: 
      experience: [1, 1, 2, 3, 4, 4, 5] 
    ansible.builtin.debug:
      msg: "removing duplicates {{experience | unique}}"

  - name: print min and max
    vars: 
      age: [19, 10, 40, 50] 
    ansible.builtin.debug:
      msg: "min is : {{age | min}} and max is: {{age | max}}"

  - name: converting dictionary into list
    hosts: localhost
    vars: 
      my_dict:
        aws: "3 months"
        azure: "2 months"
        devops: "3 months"
    tasks: 
    - name: before conversion
      ansible.builtin.debug:
        msg: "Before converting  {{my_dict}}"