- name: filters
  hosts: localhost
  tasks: 
  - name: leanring filters
    ansible.builtin.debug:
      msg: "Prinitng variable {{Duration | default('3 months')}}"

  - name: lowercase
    vars: 
      course: "DEVOPS"
    ansible.builtin.debug:
      msg: "Prinitng variable {{course | lower}}"
  
  - name: uppercase
    vars: 
      course: "devops"
    ansible.builtin.debug:
      msg: "Prinitng variable {{course | upper}}"