- name: filters
  hosts: localhost
  tasks: 
  - name: leanring filters
    ansible.builtin.debug:
      msg: "Prinitng variable {{Duration | default('3 months')}}"

  - name: lowercase
    vars: 
      course: "DEVOPS"
    ansible.builtin.debug:
      msg: "converting into lowercase {{course | lower}}"
  
  - name: uppercase
    vars: 
      course: "devops"
    ansible.builtin.debug:
      msg: "converting into uppercase {{course | upper}}"

  - name: removing duplicates
    vars: 
      experience: [1, 1, 2, 3, 4, 4, 5] 
    ansible.builtin.debug:
      msg: "removing duplicates {{experience | unique}}"