- name: filters
  hosts: localhost
  tasks: 
  - name: leanring filters
    ansible.builtin.debug:
      msg: "Prinitng variable {{Duration | default('3 months')}}"

  - name: lowercase
    vars: 
    text: "LOWER"
    ansible.builtin.debug:
      msg: "Prinitng variable {{lower | LOWER}}"